### ISSUE TITLE
Badge test

### ISSUE THREAD

**Issue by jcechak** [jcechak/pokemon-league-manager#13]
Create unit tests for DAO badge class. Use in-memory database for storing test data. Be creative and try to find as many edge cases as you can. Don't forget to test usual expected behaviour as well.

**Comment by mareksabo** [comment]
Resolved by b68e4f8c9288fef17cabde5e2a9326d9c3121df2.

**Comment by mareksabo** [comment]
Resolved by b68e4f8c9288fef17cabde5e2a9326d9c3121df2.
